#!/bin/bash --login
#SBATCH --partition=workq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=10:00:00
#SBATCH --account=director2107
#SBATCH --export=MYSCRATCH,MYGROUP

CONTAINER=/group/director2107/mcheeseman/BoM_observational_data_generation/preprocess/gdal_python3.sif

##====================================================================================================
##---------------------------    Do not change anything below this line    ---------------------------
##====================================================================================================

##
## Set up Singularity
##

module load singularity/3.3.0

export SINGULARITY_CACHEDIR=$MYGROUP
export SINGULARITY_TMPDIR=$MYSCRATCH

##
## Run preprocessing script
##

srun -n 1 --export=ALL -u singularity exec --bind /group,/scratch $CONTAINER python3 ./test.py 

